[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "madonna"
version = "0.1.3"
description = "Python semver parsing library."
authors = ["Tom Fleet <tomfleet2018@gmail.com>"]
license = "MIT License"
homepage = "https://github.com/FollowTheProcess/madonna"
readme = "README.md"
repository = "https://github.com/FollowTheProcess/madonna"
documentation = "https://FollowTheProcess.github.io/madonna/"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Typing :: Typed",
]
keywords = ["semver", "parser"]
include = ["madonna/py.typed"]

[tool.poetry.urls]
Documentation = "https://FollowTheProcess.github.io/madonna/"

[tool.poetry.dependencies]
python = "^3.7"
typing-extensions = { version = "^3.10.0.2", python = "<3.8" }

[tool.poetry.dev-dependencies]
pytest = "6.2.5"
bump2version = "1.0.1"
flake8 = "4.0.1"
flake8-bugbear = "22.1.11"
isort = "5.10.1"
nox = "2022.1.7"
black = "21.12b0"
coverage-badge = "1.1.0"
coverage = { extras = ["toml"], version = "6.2.0" }
mypy = "0.931"
mkdocs = "1.2.3"
mkdocs-material = "8.1.7"
mkdocstrings = "0.16.2"
pre-commit = "2.17.0"
ward = "0.65.0-beta.0"


[tool.isort]
profile = "black"
multi_line_output = 3

[tool.coverage.run]
omit = ["*__init__.py"]
branch = true

[tool.mypy]
files = ["madonna/**/*.py", "noxfile.py"]

ignore_missing_imports = true
strict = true
disallow_untyped_decorators = false
pretty = true

[[tool.mypy.overrides]]
module = ["tests.*", "pytests.*"]
ignore_errors = true

[tool.pycln]
path = "/madonna"
expand_stars = true
all = true
no_gitignore = false

[tool.bandit]
skips = ["B106"]

[tool.ward]
path = "tests"
order = "random"
test-output-style = "dots-module"
